### ISSUE TITLE
update ci status in readme

### ISSUE THREAD

**Issue by whyvrafvr** [fairhive-labs/go-pixelart#24]

**Comment by Soumya-Kushwaha** [comment]
Hey @juliensie ci status exactly means?

**Comment by Soumya-Kushwaha** [comment]
Hey @juliensie ci status exactly means?

**Comment by whyvrafvr** [comment]
CI stands for Continuous Integration. 

I've refactored CI/CD pipeline but now docker image name and status badges must be changed in README.
